# Generated by Django 5.1.1 on 2024-09-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedpost',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
