# Generated by Django 5.1.1 on 2024-09-14 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['sender', 'receiver'], name='friendship__sender__9747dd_idx'),
        ),
    ]
