# Generated by Django 5.1.1 on 2024-09-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='post',
        ),
        migrations.AddField(
            model_name='notification',
            name='post_Id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
